# -*- coding: utf-8 -*-
"""score_fusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DF5Fa9AtA2f9Femn_2YvRvO8H3qX1csL
"""

import os
import numpy as np
import re 

edict = {}
edict[0] = 'Angry'
edict[1] = 'Disgust'
edict[2] = 'Fear'
edict[3] = 'Happy'
edict[4] = 'Neutral'
edict[5] = 'Sad'
edict[6] = 'Surprise'

def compute_fusion(pred_1, pred_2, pred_3,pred_4, pred_5, p1, p2,p3, p4):
    fusion_pred = p1*pred_1 + p2*pred_2 + p3*pred_3 + p4*pred_4 + (1-p1-p2-p3-p4)*pred_5
    return fusion_pred 

pred_p = compute_fusion(c3d_qiyi_res, c3d_afew_2_res,lstm_res,c3d_afew_1_res, audio_res ,0.05,0.15,0.25,0.03)
pred_l = np.argmax(pred_p ,1)
ans = edict[pred_l]